export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_REQUESTED = 'FETCH_ORDERS_REQUESTED'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'

export const PURCHASE_BURGER_REQUESTED = 'PURCHASE_BURGER_REQUESTED'
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'


