export const SIGNIN_REQUESTED = 'SIGNIN_REQUESTED'
export const SIGNIN_START = 'SIGNIN_START'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'
export const SIGNOUT_START = 'SIGNOUT_START'
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH'
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT"
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE"